---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_solo
  environments_path: environments
  coobooks_path:
    -cookbooks

  ohai:
   disabled_plugins: ["passwd"]

platforms:
- name: centos-7
  driver_config:
    privileged: true
    memory: 1512m
    volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
    provision_command:
      - echo "root:password" | chpasswd
      - sed -i 's/Defaults   requiretty/#Defaults   requiretty/g' /etc/sudoers
suites:
  - name: default
    run_list:
      - recipe[c2b2_website::installapache]
